title: Or Bashan
logo: /figs/HeadShot.png
description: Welcome to my GitHub Portfolio! Explore a curated collection of my projects, showcasing my skills in data science, software development, data analysis, and more.
#show_downloud: true
theme: jekyll-theme-minimal
